# Generated by Django 3.2.12 on 2022-03-30 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_category_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_page_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший секцию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_section_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший тег', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_tag_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
